name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/web/Frontend
            echo "Git PULL"
            git pull origin main
            echo "NPM Install"
            npm install
            echo "NPM Run Build"
            npm run build
            echo "Go Dist"
            cd /home/ubuntu/web/Frontend/dist
            echo "Copy to nginx Root"
            sudo cp -r * /var/www/html/
